/*
Navicat MySQL Data Transfer

Source Server         : local
Source Server Version : 50090
Source Host           : localhost:3306
Source Database       : 621m

Target Server Type    : MYSQL
Target Server Version : 50090
File Encoding         : 65001

Date: 2016-05-30 14:04:11
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for book
-- ----------------------------
DROP TABLE IF EXISTS `book`;
CREATE TABLE `book` (
  `id` int(11) NOT NULL auto_increment,
  `file_name` varchar(50) default NULL,
  `name` varchar(50) default NULL,
  `author` varchar(50) default NULL,
  `chaodai` varchar(50) default NULL,
  `tm_year` varchar(50) default NULL,
  `about` longtext,
  `type` varchar(50) default NULL,
  `catalog_id` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `catalog` (`catalog_id`),
  CONSTRAINT `catalog` FOREIGN KEY (`catalog_id`) REFERENCES `catalog` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=932 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of book
-- ----------------------------
INSERT INTO `book` VALUES ('1', '000-神农本草经.txt', '神农本草经', '孙星衍  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('2', '001-吴普本草.txt', '吴普本草', '吴普  ', '魏晋  ', '公元420年—589  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('3', '002-本草经集注.txt', '本草经集注', '陶弘景  ', '南朝·梁  ', '公元502-557年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('4', '003-新修本草.txt', '新修本草', '苏敬等20余人编写  ', '唐  ', '公元659年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('5', '004-食疗本草.txt', '食疗本草', '孟显  ', '唐  ', '公元618-907年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('6', '005-海药本草.txt', '海药本草', '李珣  ', '五代  ', '公元907-960年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('7', '006-本草图经.txt', '本草图经', '苏颂  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('8', '007-本草衍义.txt', '本草衍义', '寇宗奭  ', '宋·政和六年  ', '公元1116年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('9', '008-汤液本草.txt', '汤液本草', '王好古  ', '元  ', '公元1298年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('10', '009-饮膳正要.txt', '饮膳正要', '忽思慧  ', '元  ', '公元1314-1320年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('11', '010-滇南本草.txt', '滇南本草', '兰茂  ', '明  ', '公元1396-1476年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('12', '', '本草品汇精要', '刘文泰', '明', '1503', '', 'txt', '1');
INSERT INTO `book` VALUES ('13', '012-本草蒙筌.txt', '本草蒙筌', '陈嘉谟  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('14', '013-本草纲目.txt', '本草纲目', '李时珍  ', '明·万历六年  ', '公元1578年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('15', '014-本草乘雅半偈.txt', '本草乘雅半偈', '卢之颐  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('16', '015-本草征要.txt', '本草征要', '李中梓  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('17', '016-本草易读.txt', '本草易读', '汪讱庵  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('18', '017-本草新编.txt', '本草新编', '陈士铎  ', '清·公元1644-1911年  ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('19', '018-本草备要.txt', '本草备要', '汪昂  ', '清·公元1644-1911年  ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('20', '019-本经逢原.txt', '本经逢原', '张璐  ', '清  ', '公元1617－1700年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('21', '020-本草经解.txt', '本草经解', '叶桂  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('22', '021-本草从新.txt', '本草从新', '吴仪洛  ', '清·公元1644-1911年  ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('23', '022-神农本草经百种录.txt', '神农本草经百种录', '徐大椿  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('24', '023-本草纲目拾遗.txt', '本草纲目拾遗', '赵学敏  ', '清  ', '公元1765年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('25', '024-本草崇原.txt', '本草崇原', '着者张志聪殁而书未成，后由弟子高世栻续成  ', '清·康熙十三年  ', '公元1674年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('26', '025-本草求真.txt', '本草求真', '黄宫绣  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('27', '026-神农本草经读.txt', '神农本草经读', '陈修园  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('28', '027-本草述钩元.txt', '本草述钩元', '杨时泰  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('29', '028-食鉴本草.txt', '食鉴本草', '宁原  ', ' ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('30', '029-本草思辨录.txt', '本草思辨录', '周岩  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('31', '030-本草纲目别名录.txt', '本草纲目别名录', '李时珍  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('32', '031-本草便读.txt', '本草便读', '张秉成  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('33', '032-本草撮要.txt', '本草撮要', '陈其瑞  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('34', '033-本草问答.txt', '本草问答', '唐宗海  ', '清  ', '公元1862-1918年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('35', '034-神农本草经赞.txt', '神农本草经赞', ' ', ' ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('36', '035-本草择要纲目.txt', '本草择要纲目', '蒋介繁  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('37', '036-得配本草.txt', '得配本草', '严西亭  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('38', '037-本草害利.txt', '本草害利', '凌奂  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('39', '038-本草分经.txt', '本草分经', '姚澜  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('40', '039-雷公炮炙论.txt', '雷公炮炙论', '刘宋、雷学所着  ', '南北朝  ', '公元420-581年  ', ' ', 'txt', '7');
INSERT INTO `book` VALUES ('41', '040-炮炙全书.txt', '炮炙全书', ' ', ' ', ' ', ' ', 'txt', '7');
INSERT INTO `book` VALUES ('42', '041-炮炙大法.txt', '炮炙大法', '缪希雍  ', '明  ', '公元1622年  ', ' ', 'txt', '7');
INSERT INTO `book` VALUES ('43', '042-雷公炮制药性解.txt', '雷公炮制药性解', '李士材  ', '明  ', '公元1588～1655年  ', ' ', 'txt', '7');
INSERT INTO `book` VALUES ('44', '043-濒湖炮炙法.txt', '濒湖炮炙法', '刘宋、雷学所着  ', '南北朝  ', '公元420-581年  ', ' ', 'txt', '7');
INSERT INTO `book` VALUES ('45', '044-要药分剂.txt', '要药分剂', ' ', ' ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('46', '045-珍珠囊补遗药性赋.txt', '珍珠囊补遗药性赋', '李东垣  ', '元  ', '公元1271年—1368年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('47', '046-药鉴.txt', '药鉴', '杜文燮  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '7');
INSERT INTO `book` VALUES ('48', '047-药征.txt', '药征', ' ', ' ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('49', '048-思考中医.txt', '', '刘力红', '未知', '未知', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('50', '049-五十二病方.txt', '五十二病方', ' ', '西汉  ', '公元前206年-公元8年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('51', '050-名医别录.txt', '名医别录', '陶弘景  ', '魏晋  ', '公元220-450年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('52', '051-千金翼方.txt', '千金翼方', '孙思邈  ', '唐·开耀二年  ', '公元682年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('53', '052-孙真人海上方.txt', '孙真人海上方', '孙思邈  ', '唐  ', '公元618-907年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('54', '053-外台秘要.txt', '外台秘要', '王焘  ', '唐·天宝十一年  ', '公元752年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('55', '054-医心方.txt', '医心方', '日本、丹波康赖  ', '北宋  ', '公元984年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('56', '055-太平圣惠方.txt', '太平圣惠方', '王怀隐、陈昭遇等  ', '宋·淳化三年  ', '公元992年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('57', '056-苏沈良方.txt', '苏沈良方', '沈括及苏轼撰  ', '北宋  ', '公元960-1127年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('58', '057-博济方.txt', '博济方', '王衮  ', '宋·庆历七年  ', '公元1047年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('59', '058-史载之方.txt', '史载之方', '史堪  ', '宋  ', '公元1127-1279年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('60', '059-太平惠民和剂局方.txt', '太平惠民和剂局方', '太平惠民和剂局所  ', '初刊于宋·元丰年间  ', '公元1078年-1085年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('61', '060-圣济总录.txt', '圣济总录', '由政府组织编写  ', '宋·徽宗  ', '公元1111-1117年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('62', '061-鸡峰普济方.txt', '鸡峰普济方', '张锐  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('63', '062-洪氏集验方.txt', '洪氏集验方', '洪遵  ', '宋·干道五年  ', '公元1170年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('64', '063-杨氏家藏方.txt', '杨氏家藏方', '杨倓  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('65', '064-千金宝要.txt', '千金宝要', '孙思邈  ', '唐  ', '公元618年－公元907年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('66', '065-卫生易简方.txt', '卫生易简方', '胡荧  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('67', '066-全生指迷方.txt', '全生指迷方', '王贶  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('68', '067-仁斋直指方论（附补遗）.txt', '仁斋直指方论（附补遗）', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('69', '068-瑞竹堂经验方.txt', '瑞竹堂经验方', '沙图穆秀克  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('70', '069-世医得效方.txt', '世医得效方', '危亦林  ', '天历元年  ', '公元1328年-1337年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('71', '070-奇效良方.txt', '奇效良方', '董宿  ', '明·成化六年  ', '公元1470年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('72', '071-医方集宜.txt', '医方集宜', '丁毅  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('73', '072-医方考.txt', '医方考', '吴昆  ', '明代  ', '公元1584年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('74', '073-增广和剂局方药性总论.txt', '增广和剂局方药性总论', '佚名  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('75', '074-普济方.txt', '普济方', '朱梓  ', '明·永乐四年  ', '公元1406年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('76', '075-肘后备急方.txt', '肘后备急方', '葛洪  ', '东晋  ', '公元317-420年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('77', '076-普济本事方.txt', '普济本事方', '许叔微  ', '南宋  ', '公元1132年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('78', '077-严氏济生方.txt', '严氏济生方', '严用和  ', '宋·宝元  ', '公元1253年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('79', '078-药征续编.txt', '药征续编', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('80', '079-仁术便览.txt', '仁术便览', '张洁  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('81', '080-中医之钥.txt', '', '未知', '未知', '未知', ' ', 'txt', null);
INSERT INTO `book` VALUES ('82', '081-祖剂.txt', '祖剂', '施沛  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('83', '082-古今名医方论.txt', '古今名医方论', '罗美。  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('84', '083-种福堂公选良方.txt', '种福堂公选良方', '叶桂原着、华岫云编  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('85', '084-汤头歌诀.txt', '汤头歌诀', '汪昂  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('86', '085-急救便方.txt', '急救便方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('87', '086-奇方类编.txt', '奇方类编', '吴世昌  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('88', '087-医方集解.txt', '医方集解', '汪昂  ', '清  ', '公元1682年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('89', '088-绛雪园古方选注.txt', '绛雪园古方选注', '王子接  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('90', '089-医方论.txt', '医方论', '费伯雄  ', '清  ', '公元1865年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('91', '090-串雅内外编.txt', '串雅内外编', '赵学敏  ', '清  ', '公元1759年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('92', '091-成方切用.txt', '成方切用', '吴仪洛  ', '清  ', '公元1761年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('93', '092-时方妙用.txt', '时方妙用', '陈念祖  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('94', '093-时方歌括.txt', '时方歌括', '陈修园  ', '清  ', '公元1801年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('95', '094-长沙方歌括.txt', '长沙方歌括', '陈念祖  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('96', '095-金匮方歌括.txt', '金匮方歌括', '陈念祖  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('97', '096-医方证治汇编歌诀.txt', '医方证治汇编歌诀', '王泰林', '清', '公元1644-1911年 ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('98', '097-验方新编.txt', '验方新编', '鲍相璈  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('99', '098-十剂表.txt', '十剂表', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('100', '099-经验丹方汇编.txt', '经验丹方汇编', '钱峻  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('101', '100-桂林古本伤寒杂病论.txt', '', '未知', '未知', '未知', ' ', 'txt', null);
INSERT INTO `book` VALUES ('102', '101-药性切用.txt', '药性切用', ' ', ' ', ' ', ' ', 'txt', '1');
INSERT INTO `book` VALUES ('103', '102-退思集类方歌注.txt', '退思集类方歌注', '王泰林  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('104', '103-华佗神方.txt', '华佗神方', '华佗  ', '汉  ', '公元前206年-公元8年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('105', '104-集验方.txt', '集验方', '洪氏  ', '宋  ', '公元960年—1279年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('106', '105-大小诸证方论.txt', '大小诸证方论', '傅青主  ', '明末清初  ', '公元１６０７──公元１６８４年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('107', '106-奇效简便良方.txt', '奇效简便良方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('108', '107-神仙济世良方.txt', '神仙济世良方', ' ', ' ', ' ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('109', '108-是斋百一选方.txt', '是斋百一选方', '王璆原  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('110', '109-小品方.txt', '小品方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('111', '110-惠直堂经验方.txt', '惠直堂经验方', '陶承熹  ', '清·公元1644-1911年  ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('112', '111-绛囊撮要.txt', '绛囊撮要', '云川道人  ', '清  ', '公元1644年-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('113', '112-经验奇方.txt', '经验奇方', '刘一明  ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('114', '113-古方汇精.txt', '古方汇精', '爱虚老人  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('115', '114-外治寿世方.txt', '外治寿世方', '邹存检  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('116', '115-文堂集验方.txt', '文堂集验方', '罗浮山人  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('117', '116-回生集.txt', '回生集', '陈杰  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('118', '117-本草简要方.txt', '本草简要方', '张宗祥  ', '现代  ', '公元1938年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('119', '118-增订医方歌诀.txt', '增订医方歌诀', '王泰林  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('120', '119-济世神验良方.txt', '济世神验良方', '佚名  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('121', '120-伤寒恒论.txt', '伤寒恒论', '鄭欽安  闡釋·唐步祺  ', '清  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('122', '121-医方歌括.txt', '医方歌括', '王泰林', '清', '公元1644-1911年', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('123', '122-医方简义.txt', '医方简义', '王清源  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('124', '123-女科切要.txt', '女科切要', '吴道源  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('125', '124-傅青主女科歌括.txt', '傅青主女科歌括', '傅山  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('126', '125-产宝.txt', '产宝', '咎段  ', '唐  ', '公元618-907年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('127', '126-女科百问.txt', '女科百问', '宋仲甫  ', '南宋  ', '公元420-479年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('128', '127-钱氏秘传产科方书名试验录.txt', '钱氏秘传产科方书名试验录', ' ', ' ', ' ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('129', '128-妇人大全良方.txt', '妇人大全良方', '陈自明  ', '南宋·嘉熙元年  ', '公元1237年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('130', '129-沈氏女科辑要.txt', '沈氏女科辑要', '沈又彭  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('131', '130-济生集.txt', '济生集', ' ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('132', '131-婴童百问.txt', '婴童百问', '鲁伯嗣  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('133', '132-女科证治准绳.txt', '女科证治准绳', '王肯堂  ', '明  ', '公元1368──公元1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('134', '133-小儿药证直诀.txt', '小儿药证直诀', '钱乙  ', '宋  ', '公元1032～ll13年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('135', '134-幼科切要.txt', '幼科切要', '王锡鑫  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('136', '135-婴儿论.txt', '婴儿论', '周士祢  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('137', '136-活幼心书.txt', '活幼心书', '曹世荣  ', '元  ', '公元1252-1332年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('138', '137-儿科要略.txt', '儿科要略', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('139', '138-儿科萃精.txt', '儿科萃精', '陈守真  ', '民国  ', '公元1930年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('140', '139-痧疹辑要.txt', '痧疹辑要', '叶霖  ', ' ', '不详  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('141', '140-小儿推拿广意.txt', '小儿推拿广意', '熊应雄  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('142', '141-幼科证治准绳.txt', '幼科证治准绳', '王肯堂  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('143', '142-女科旨要.txt', '女科旨要', '雪岩禅师  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('144', '143-女科折衷纂要.txt', '女科折衷纂要', '凌德  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('145', '144-女科指要.txt', '女科指要', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('146', '145-女科指掌.txt', '女科指掌', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('147', '146-女科要旨.txt', '女科要旨', '陈念祖  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('148', '147-女科秘旨.txt', '女科秘旨', '轮印禅师  ', '清  ', '公元1771──公元1711年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('149', '148-女科秘要.txt', '女科秘要', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('150', '149-女科经纶.txt', '女科经纶', '萧埙  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('151', '150-女科精要.txt', '女科精要', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('152', '151-女科撮要.txt', '女科撮要', '薛立斋  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('153', '152-小儿痘疹方论.txt', '小儿痘疹方论', '陈文中  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('154', '153-小儿卫生总微论方.txt', '小儿卫生总微论方', '不详  ', '宋  ', '公元1158年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('155', '154-内府秘传经验女科.txt', '内府秘传经验女科', '龚廷贤  ', '明  ', '公元1716年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('156', '155-幼幼集成.txt', '幼幼集成', '陈复正  ', '清  ', '公元1750年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('157', '156-幼幼新书.txt', '幼幼新书', '刘昉  ', '宋  ', '公元1150年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('158', '157-幼科心法要诀.txt', '幼科心法要诀', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('159', '158-幼科折衷.txt', '幼科折衷', '秦景明  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('160', '159-幼科指南.txt', '幼科指南', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('161', '160-幼科推拿秘书.txt', '幼科推拿秘书', '骆如龙  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('162', '161-幼科发挥.txt', '幼科发挥', '万全  ', '明  ', '公元1549 年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('163', '162-幼科概论.txt', '幼科概论', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('164', '163-幼科类萃.txt', '幼科类萃', '王銮  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('165', '164-幼科铁镜.txt', '幼科铁镜', '夏禹铸  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('166', '165-竹泉生女科集要.txt', '竹泉生女科集要', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('167', '166-儿科醒.txt', '儿科醒', '芝屿樵客  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('168', '167-保幼新编.txt', '保幼新编', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('169', '168-保婴撮要.txt', '保婴撮要', '薛铠  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('170', '169-活幼口议.txt', '活幼口议', '曾世荣  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('171', '170-胎产心法.txt', '胎产心法', '闵纯玺  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('172', '171-胎产指南.txt', '胎产指南', '张曜孙  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('173', '172-胎产秘书.txt', '胎产秘书', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('174', '173-家传女科经验摘奇.txt', '家传女科经验摘奇', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('175', '174-妇人规.txt', '妇人规', '攻介宾  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('176', '175-妇科心法要诀.txt', '妇科心法要诀', '吴谦等  ', '清·乾隆  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('177', '176-妇科秘方.txt', '妇科秘方', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('178', '177-妇科秘书.txt', '妇科秘书', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('179', '178-妇科问答.txt', '妇科问答', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('180', '179-专治麻痧初编.txt', '专治麻痧初编', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('181', '180-张氏妇科.txt', '张氏妇科', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('182', '181-产鉴.txt', '产鉴', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('183', '182-陈氏幼科秘诀.txt', '陈氏幼科秘诀', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('184', '183-麻科活人全书.txt', '麻科活人全书', '谢玉琼恩  ', '清  ', '公元1748年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('185', '184-麻疹备要方论.txt', '麻疹备要方论', '吴砚丞  ', '清  ', '公元1853年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('186', '185-麻疹阐注.txt', '麻疹阐注', '张霞溪  ', '清  ', '公元1840年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('187', '186-痘疹心法要诀.txt', '痘疹心法要诀', '吴谦等  ', '清  ', '公元1742年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('188', '187-评注产科心法.txt', '评注产科心法', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('189', '188-慈幼便览.txt', '慈幼便览', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('190', '189-慈幼新书.txt', '慈幼新书', '程云鹏  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('191', '190-毓麟验方.txt', '毓麟验方', '不详', '不详', '不详', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('192', '190-毓麟验方.txt.old', '', '未知', '未知', '未知', ' ', 'txt', null);
INSERT INTO `book` VALUES ('193', '191-经验麻科.txt', '经验麻科', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('194', '192-达生编.txt', '达生编', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('195', '193-盘珠集胎产症治.txt', '盘珠集胎产症治', '单南山  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('196', '194-竹林女科证治.txt', '竹林女科证治', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('197', '195-原要论.txt', '原要论', '袁氏（佚名）  ', '清  ', '公元1828年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('198', '196-产后十八论.txt', '产后十八论', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('199', '197-脚气治法总要.txt', '脚气治法总要', '董汲  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('200', '198-济阴纲目.txt', '济阴纲目', '武之望  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('201', '199-卫生家宝产科备要.txt', '卫生家宝产科备要', '朱端章  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('202', '200-邯郸遗稿.txt', '邯郸遗稿', '赵献可  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('203', '201-鬻婴提要说.txt', '鬻婴提要说', ' 未知', ' 未知', ' 未知', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('204', '202-颅囟经.txt', '颅囟经', '佚名  ', '东汉  ', '公元25-220年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('205', '203-婴童类萃.txt', '婴童类萃', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('206', '204-医林改错.txt', '医林改错', '王清任  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('207', '205-金匮翼.txt', '金匮翼', '尤怡  ', '清  ', '公元1768年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('208', '206-养老奉亲书.txt', '养老奉亲书', '陈直  ', '宋  ', '公元960-1279年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('209', '207-医门法律.txt', '医门法律', '喻昌  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('210', '208-笔花医镜.txt', '笔花医镜', '江涵暾  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('211', '209-血证论.txt', '血证论', '唐容川  ', '清  ', '公元1884年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('212', '210-外科精义.txt', '外科精义', '齐德之  ', '元  ', '公元1271～1368年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('213', '211-立斋外科发挥.txt', '立斋外科发挥', '薛己  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('214', '212-外科枢要.txt', '外科枢要', '薛己  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('215', '213-杂病心法要诀.txt', '杂病心法要诀', '吴谦等  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('216', '214-跌损妙方.txt', '跌损妙方', '异远真人  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('217', '215-杂病广要.txt', '杂病广要', '日本·丹波元坚撰  ', '清  ', '公元1853年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('218', '216-江氏伤科学.txt', '江氏伤科学', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('219', '217-伤科大成.txt', '伤科大成', '赵濂  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('220', '218-跌打秘方.txt', '跌打秘方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('221', '219-跌打损伤方.txt', '跌打损伤方', '杨成博  ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('222', '220-外科集验方.txt', '外科集验方', '赵宜真  ', '明·洪武戊午年  ', '公元1378年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('223', '221-余无言.txt', '余无言', '余无言  ', '近代 ', '公元1900～1963年  ', '', 'txt', null);
INSERT INTO `book` VALUES ('224', '222-跌打损伤回生集.txt', '跌打损伤回生集', '胡青昆  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('225', '223-疡医大全.txt', '疡医大全', '顾世澄  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('226', '224-傅青主男科重编考释.txt', '傅青主男科重编考释', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('227', '225-疡科心得集.txt', '疡科心得集', '高秉钧  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('228', '226-外科大成.txt', '外科大成', '祁坤  ', '清  ', '公元1665年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('229', '227-阴证略例.txt', '阴证略例', '王好古  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('230', '228-发背对口治诀论.txt', '发背对口治诀论', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('231', '229-集验背疽方.txt', '集验背疽方', '李迅  ', '宋·庆元二年  ', '公元1196年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('232', '230-外科正宗.txt', '外科正宗', '陈实功  ', '明  ', '公元1617年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('233', '231-中风论.txt', '中风论', '熊笏  ', '清·嘉庆  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('234', '232-内外伤辨.txt', '内外伤辨', '李杲  ', '金  ', '公元1115-1234年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('235', '233-内科摘要.txt', '内科摘要', '薛己  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('236', '234-少林真传伤科秘方.txt', '少林真传伤科秘方', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('237', '235-仙授理伤续断秘方.txt', '仙授理伤续断秘方', '蔺道人  ', '唐代  ', '公元618-907年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('238', '236-外科十三方考.txt', '外科十三方考', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('239', '237-外科心法要诀.txt', '外科心法要诀', '吴谦等  ', '清  ', '公元1742年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('240', '238-外科方外奇方.txt', '外科方外奇方', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('241', '239-外科全生集.txt', '外科全生集', '王洪绪  ', '清  ', '公元1740年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('242', '240-外科启玄.txt', '外科启玄', '申斗垣  ', '明  ', '公元1604年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('243', '241-外科理例.txt', '外科理例', '汪机  ', '明·嘉靖二年  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('244', '242-外科传薪集.txt', '外科传薪集', '马培之  ', '清  ', '公元1912-1949年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('245', '243-外科精要.txt', '外科精要', '陈自明  ', '宋  ', '公元1263年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('246', '244-外科选要.txt', '外科选要', '徐直銈  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('247', '245-外科医镜.txt', '外科医镜', '高思敬  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('248', '246-正骨心法要旨.txt', '正骨心法要旨', '吴谦等  ', '清  ', '公元1742年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('249', '247-正体类要.txt', '正体类要', '薛己  ', '明  ', '公元1529年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('250', '248-何氏虚劳心传.txt', '何氏虚劳心传', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('251', '249-周慎斋遗书.txt', '周慎斋遗书', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('252', '250-奇经八脉考.txt', '奇经八脉考', '李时珍  ', '明·万历五年  ', '公元1577年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('253', '251-金疮秘传禁方.txt', '金疮秘传禁方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('254', '252-金疮跌打接骨药性秘书.txt', '金疮跌打接骨药性秘书', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('255', '253-青囊秘诀.txt', '青囊秘诀', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('256', '254-急救良方.txt', '急救良方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('257', '255-急救广生集.txt', '急救广生集', '程鹏程  ', '清  ', '公元1805年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('258', '256-订正太素脉秘诀.txt', '订正太素脉秘诀', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('259', '257-症因脉治.txt', '症因脉治', '朱丹溪  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('260', '258-秘传外科方.txt', '秘传外科方', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('261', '259-秘传刘伯温家藏接骨金疮禁方.txt', '秘传刘伯温家藏接骨金疮禁方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('262', '260-脉症治方.txt', '脉症治方', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('263', '261-脉确.txt', '脉确', '黄琳述  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('264', '262-接骨手法.txt', '', '未知', '未知', '未知', ' ', 'txt', null);
INSERT INTO `book` VALUES ('265', '263-救伤秘旨.txt', '救伤秘旨', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('266', '264-理虚元鉴.txt', '理虚元鉴', '汪绮石  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('267', '265-虚损启微.txt', '虚损启微', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('268', '266-诊脉三十二辨.txt', '诊脉三十二辨', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('269', '267-伤科方书.txt', '伤科方书', '江考卿  ', '清  ', '公元1840年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('270', '268-伤科汇纂.txt', '伤科汇纂', '胡廷光  ', '清  ', '公元1808年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('271', '269-伤科补要.txt', '伤科补要', '钱潢  ', '清  ', '公元1808年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('272', '270-慎柔五书.txt', '慎柔五书', '胡慎柔  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('273', '271-杨成博先生遗留穴道秘书.txt', '杨成博先生遗留穴道秘书', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('274', '272-痰火点雪.txt', '痰火点雪', '龚居中  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('275', '273-万氏秘传外科心法.txt', '万氏秘传外科心法', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('276', '274-解围元薮.txt', '解围元薮', '沈之问  ', '明  ', '公元1550年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('277', '275-刘涓子鬼遗方.txt', '刘涓子鬼遗方', '龚庆宣  ', '南齐  ', '公元479-502年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('278', '276-疯门全书.txt', '疯门全书', '肖晓亭  ', '清  ', '公元1836年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('279', '277-医略.txt', '中医瑰宝苑 医略十三篇', '吴县潘世恩撰  ', '  ', '  ', '', 'txt', null);
INSERT INTO `book` VALUES ('280', '278-增订十药神书.txt', '增订十药神书', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('281', '279-疠疡机要.txt', '疠疡机要', '薛己  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('282', '280-医学从众录.txt', '医学从众录', '陈修园  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('283', '281-疡科纲要.txt', '疡科纲要', '张山雷  ', '民国初年  ', '公元1912-至今  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('284', '282-医门补要.txt', '医门补要', '赵濂  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('285', '283-医源.txt', '瑰宝苑 《医源》', '芬余氏遗著  ', '  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('286', '284-仙传外科集验方.txt', '仙传外科集验方', '赵宜真  ', '元末明初  ', '公元1382年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('287', '285-外科十法.txt', '外科十法', '朱世杰  ', '清  ', '公元1644～1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('288', '286-脉诀乳海.txt', '脉诀乳海', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('289', '287-脉诀考证.txt', '脉诀考证', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('290', '288-痰疠法门.txt', '痰疠法门', '李子毅  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('291', '289-证治汇补.txt', '证治汇补', '李用粹  ', '清  ', '公元1687年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('292', '290-外科证治全书.txt', '外科证治全书', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('293', '291-眼科秘诀.txt', '眼科秘诀', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('294', '292-银海精微.txt', '银海精微', '孙思邈  ', '唐  ', '公元682年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('295', '293-审视瑶函.txt', '审视瑶函', '傅仁宇  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('296', '294-目经大成.txt', '目经大成', '黄庭镜草成此书，此后四易其稿，但未付梓。弟子邓学礼得悉此书后于嘉庆十年刊行  ', '清·乾隆六年  ', '公元1741年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('297', '295-针灸大全.txt', '针灸大全', '徐凤  ', '明·正统四年  ', '公元1439 年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('298', '296-扁鹊神应针灸玉龙经.txt', '扁鹊神应针灸玉龙经', '王国瑞  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('299', '297-针灸易学.txt', '针灸易学', '李守先  ', '清·嘉庆三年  ', '公元1798年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('300', '298-针灸聚英.txt', '针灸聚英', '高武  ', '明·嘉靖八年  ', '公元1529年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('301', '299-针灸大成.txt', '针灸大成', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('302', '300-针灸逢源.txt', '针灸逢源', '李学川  ', '清·嘉庆二十年  ', '公元1815年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('303', '301-针灸甲乙经.txt', '针灸甲乙经', '皇甫谧  ', '晋  ', '公元256年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('304', '302-针经节要.txt', '针经节要', '杜思敬  ', '元  ', '公元1315年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('305', '303-李翰卿.txt', '中医瑰宝苑 《李翰卿》yi', '李翰卿  ', '现代  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('306', '304-杨敬斋针灸全书.txt', '杨敬斋针灸全书', '陈言  ', '明·万历十九年  ', '公元1591年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('307', '305-宋本备急灸法.txt', '宋本备急灸法', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('308', '306-刺灸心法要诀.txt', '刺灸心法要诀', '吴谦  ', '清  ', '公元1742年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('309', '307-一草亭目科全书.txt', '一草亭目科全书', '邓苑  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('310', '308-口齿类要.txt', '口齿类要', '薛己  ', '明  ', '公元1528年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('311', '309-子午流注针经.txt', '子午流注针经', '何若愚撰、阎明广注  ', '金  ', '撰年不详  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('312', '310-子午流注说难.txt', '子午流注说难', '吴棹仙  ', '近代  ', '公元1956年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('313', '311-尤氏喉科秘书.txt', '尤氏喉科秘书', '王士雄  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('314', '312-尤氏喉症指南.txt', '尤氏喉症指南', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('315', '313-白喉全生集.txt', '白喉全生集', '李纪方  ', '清  ', '公元1882年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('316', '314-白喉条辨.txt', '白喉条辨', '陈葆善  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('317', '315-银海指南.txt', '银海指南', '顾锡  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('318', '316-普济方·针灸.txt', '普济方·针灸', '朱梓  ', '明·永乐四年  ', '公元1406年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('319', '317-灸法秘传.txt', '灸法秘传', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('320', '318-走马急疳真方.txt', '走马急疳真方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('321', '319-明目至宝.txt', '明目至宝', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('322', '320-金针秘传.txt', '金针秘传', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('323', '321-灵药秘方.txt', '灵药秘方', '师成子  ', '清  ', '', '', 'txt', null);
INSERT INTO `book` VALUES ('324', '322-重订囊秘喉书.txt', '重订囊秘喉书', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('325', '323-重楼玉钥.txt', '重楼玉钥', '郑梅涧  ', '清·乾隆年间  ', '公元1838年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('326', '324-重楼玉钥续编.txt', '重楼玉钥续编', '方成培  ', '清  ', '公元1838年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('327', '325-原机启微.txt', '原机启微', '倪维德  ', '元  ', '公元1370年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('328', '326-神灸经纶.txt', '神灸经纶', '吴亦鼎  ', '清·咸丰六年  ', '公元1851年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('329', '327-神应经.txt', '神应经', '陈会撰、刘瑾补辑  ', '明·洪熙元年  ', '公元1425年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('330', '328-秘传眼科龙木论.txt', '秘传眼科龙木论', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('331', '329-针灸神书.txt', '针灸神书', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('332', '330-针灸素难要旨.txt', '针灸素难要旨', '高武  ', '明·嘉靖十六年  ', '公元1537年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('333', '331-针灸问对.txt', '针灸问对', '汪机  ', '明  ', '嘉靖九年·公元1530年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('334', '332-针灸集成.txt', '针灸集成', '廖润鸿  ', '清·同治十三年  ', '公元1874年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('335', '333-针灸资生经.txt', '针灸资生经', '王执中  ', '南宋·嘉定十二年  ', '公元1220年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('336', '334-针经指南.txt', '针经指南', '窦汉卿  ', '元·元贞元年  ', '公元1295年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('337', '335-巢氏病源补养宣导法.txt', '巢氏病源补养宣导法', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('338', '336-推拿抉微.txt', '推拿抉微', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('339', '337-理瀹骈文.txt', '理瀹骈文', '吴师机  ', '清  ', '公元1864年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('340', '338-异授眼科.txt', '异授眼科', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('341', '339-眼科心法要诀.txt', '眼科心法要诀', '吴谦等  ', '清  ', '公元1742年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('342', '340-眼科阐微.txt', '眼科阐微', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('343', '341-喉舌备要秘旨.txt', '喉舌备要秘旨', '佚名  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('344', '342-喉科指掌.txt', '喉科指掌', '张宗良  ', '清  ', '公元1757年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('345', '343-喉科秘诀.txt', '喉科秘诀', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('346', '344-喉科集腋.txt', '喉科集腋', '沈青芝  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('347', '345-焦氏喉科枕秘.txt', '焦氏喉科枕秘', ' ', ' ', ' ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('348', '346-黄帝明堂灸经.txt', '黄帝明堂灸经', '不详  ', '唐代  ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('349', '347-经穴汇解.txt', '经穴汇解', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('350', '348-经络全书.txt', '经络全书', '沈子禄、徐师曾撰  ', '明·万历四年  ', '公元1576年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('351', '349-经络考.txt', '经络考', '张三锡  ', '明·万历三十七年  ', '公元1609年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('352', '350-经络汇编.txt', '经络汇编', '翟良  ', '明·崇祯元年  ', '公元1628年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('353', '351-包氏喉证家宝.txt', '包氏喉证家宝', '包三述  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('354', '352-炙膏肓腧穴法.txt', '炙膏肓腧穴法', ' ', ' ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('355', '353-凌门传授铜人指穴.txt', '凌门传授铜人指穴', '不详  ', '清·康熙前  ', '公元1644-1911年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('356', '354-厘正按摩要术.txt', '厘正按摩要术', '张振鉴  ', '清  ', ' ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('357', '355-灵枢经脉翼.txt', '灵枢经脉翼', '夏英  ', '明·弘治十年  ', '公元1497年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('358', '356-广嗣要语.txt', '广嗣要语', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('359', '357-局方发挥.txt', '局方发挥', '朱丹溪著   ', '  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('360', '358-西方子明堂灸经.txt', '西方子明堂灸经', '不详  ', '元·至正末年  ', '公元1368年  ', ' ', 'txt', '8');
INSERT INTO `book` VALUES ('361', '359-友渔斋医话.txt', '友渔斋医话', '黄凯钧  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('362', '360-徐批叶天士晚年方案真本.txt', '徐批叶天士晚年方案真本', '叶天士  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('363', '361-吴鞠通医案.txt', '吴鞠通医案', '吴鞠通  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('364', '362-冷庐医话.txt', '冷庐医话', '陆以湉  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('365', '363-柳洲医话.txt', '柳洲医话', '魏之琇  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('366', '364-医贯.txt', '医贯', '赵献可  ', '明  ', '公元1687年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('367', '365-古今医案按.txt', '古今医案按', '俞震篡  ', '清  ', '公元1778年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('368', '366-侣山堂类辩.txt', '侣山堂类辩', '张志聪  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('369', '367-临证指南医案.txt', '临证指南医案', '叶桂  ', '清  ', '公元1746年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('370', '368-存存斋医话稿.txt', '存存斋医话稿', '赵晴  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('371', '369-丹溪治法心要.txt', '丹溪治法心要', '朱震亨、  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('372', '370-医经溯洄集.txt', '医经溯洄集', '王履  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('373', '371-叶天士医案精华.txt', '叶天士医案精华', ' ', ' ', ' ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('374', '372-一得集.txt', '一得集', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('375', '373-丁甘仁医案.txt', '丁甘仁医案', ' ', ' ', ' ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('376', '374-三家医案合刻.txt', '三家医案合刻', '吴金寿  ', '清  ', '公元1831年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('377', '375-上池杂说.txt', '上池杂说', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('378', '376-也是山人医案.txt', '也是山人医案', ' ', ' ', ' ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('379', '377-客尘医话.txt', '客尘医话', '讦寿乔  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('380', '378-王氏医案绎注.txt', '王氏医案绎注', '任锡庚  ', '清  ', '公元1644年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('381', '379-市隐庐医学杂着.txt', '市隐庐医学杂着', '王严士  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('382', '380-未刻本叶氏医案.txt', '未刻本叶氏医案', '叶天士  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('383', '381-先哲医话.txt', '先哲医话', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('384', '382-回春录.txt', '回春录', '王士维  ', '清  ', '公元1824年-1857年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('385', '383-何澹安医案.txt', '何澹安医案', ' ', ' ', ' ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('386', '384-吴医汇讲.txt', '吴医汇讲', '唐大烈  ', '清  ', '公元1792-1801年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('387', '385-奇症汇.txt', '奇症汇', '沈源  ', '清  ', '公元1786年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('388', '386-知医必辨.txt', '知医必辨', '李冠仙  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('389', '387-肯堂医论.txt', '肯堂医论', '王肯堂  ', '明  ', '公元1602年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('390', '388-花韵楼医案.txt', '花韵楼医案', '顾德华　　　　　　　  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('391', '389-证治心传.txt', '证治心传', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('392', '390-辨证汇编.txt', '中医瑰宝苑 辨症汇编', '山野居士  ', '  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('393', '391-眉寿堂方案选存.txt', '眉寿堂方案选存', '叶天士  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('394', '392-研经言.txt', '研经言', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('395', '393-重订灵兰要览.txt', '重订灵兰要览', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('396', '394-重庆堂随笔.txt', '重庆堂随笔', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('397', '395-凌临灵方.txt', '凌临灵方', '凌晓五  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('398', '396-孙文垣医案.txt', '孙文垣医案', '孙一奎  ', '清  ', '公元1522~1619年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('399', '397-塘医话.txt', '塘医话', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('400', '398-马培之医案.txt', '马培之医案', '马培之  ', '清  ', '公元1893年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('401', '399-张聿青医案.txt', '张聿青医案', '张聿青  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('402', '400-张畹香医案.txt', '张畹香医案', '张畹香  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('403', '401-曹仁伯医案论.txt', '曹仁伯医案论', '曹存心  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('404', '402-热病衡正.txt', '热病衡正', '柴中元', '  ', '  ', '', 'txt', null);
INSERT INTO `book` VALUES ('405', '403-寓意草.txt', '寓意草', '喻昌  ', '清  ', '公元1645年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('406', '404-程杏轩医案.txt', '程杏轩医案', '程杏轩  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('407', '405-慎疾刍言.txt', '慎疾刍言', '徐大椿  ', '清  ', '公元1767年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('408', '406-叶选医衡.txt', '叶选医衡', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('409', '407-对山医话.txt', '对山医话', '毛对山  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('410', '408-质疑录.txt', '质疑录', '张介宾  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('411', '409-丛桂草堂医案.txt', '丛桂草堂医案', '袁焯 ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('412', '410-归砚录.txt', '归砚录', '王士雄  ', '清  ', '公元1861  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('413', '411-医原.txt', '医原', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('414', '412-医暇卮言.txt', '医暇卮言', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('415', '413-医学课儿策.txt', '医学课儿策', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('416', '414-医学读书记.txt', '医学读书记', '尤怡  ', '清  ', '公元1729年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('417', '415-医医医.txt', '医医医', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('418', '416-续名医类案.txt', '续名医类案', '魏之琇  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('419', '417-读医随笔.txt', '读医随笔', '周学海  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('420', '418-医学源流论.txt', '医学源流论', '徐大椿  ', '清·乾隆二十二年  ', '公元1757年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('421', '419-王旭高临证医案.txt', '王旭高临证医案', '王旭高  ', '清  ', '公元1644年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('422', '420-邵兰荪医案.txt', '邵兰荪医案', '邵兰荪  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('423', '421-八十一难经.txt', '八十一难经', '秦越人扁鹊  ', '西汉末  ', '公元前206年-公元8年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('424', '422-内经博议.txt', '内经博议', '罗美  ', '清  ', '公元1675年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('425', '423-素问六气玄珠密语.txt', '素问六气玄珠密语', '王冰  ', '唐  ', '公元618-907年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('426', '424-医经读.txt', '医经读', '沈又彭  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('427', '425-医经原旨.txt', '医经原旨', '薛雪  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('428', '426-素问玄机原病式.txt', '素问玄机原病式', '刘完素  ', '金  ', '公元1188年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('429', '427-类经.txt', '类经', '张介宾  ', '明·天启四年  ', '公元1624年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('430', '428-类经图翼.txt', '类经图翼', '张介宾  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('431', '429-内经知要.txt', '内经知要', '李中梓  ', '宋  ', '公元1264年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('432', '430-黄帝内经素问集注.txt', '黄帝内经素问集注', '张志聪  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('433', '431-黄帝内经灵枢集注.txt', '黄帝内经灵枢集注', '张志聪  ', '清  ', '公元1672年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('434', '432-素问病机气宜保命集.txt', '素问病机气宜保命集', '刘完素  ', '金  ', '公元1188年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('435', '433-六因条辨.txt', '六因条辨', '陆子贤  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('436', '434-素问灵枢类纂约注.txt', '素问灵枢类纂约注', '汪琥辨  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('437', '435-黄帝素问直解.txt', '黄帝素问直解', '高士宗  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('438', '436-素问经注节解.txt', '素问经注节解', '姚止庵  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('439', '437-黄帝内经素问.txt', '黄帝内经素问', '王冰次  ', '唐  ', '公元762年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('440', '438-黄帝内经素问校义.txt', '黄帝内经素问校义', '胡澍学  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('441', '439-黄帝内经太素.txt', '黄帝内经太素', '杨上善  ', '唐  ', '公元618-907年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('442', '440-中西汇通医经精义.txt', '中西汇通医经精义', '唐宗海着  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('443', '441-内经评文.txt', '内经评文', '周学海  ', '清  ', '公元1896年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('444', '442-内经药瀹.txt', '内经药瀹', '张骥  ', '清  ', '公元1675年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('445', '443-医效秘传.txt', '医效秘传', '叶桂述吴金寿校  ', '清  ', '公元1831年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('446', '444-读素问钞.txt', '读素问钞', '滑寿  ', '元  ', '公元1279-1368年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('447', '445-灵素节注类编.txt', '灵素节注类编', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('448', '446-古本难经阐注.txt', '古本难经阐注', '丁锦  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('449', '447-难经正义.txt', '难经正义', '叶霖  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('450', '448-素问识.txt', '素问识', '日本人、丹波元珍  ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('451', '449-灵枢识.txt', '灵枢识', '日本人，丹波元珍  ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('452', '450-难经经释.txt', '难经经释', '徐灵胎  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('453', '451-黄帝内经素问遗篇.txt', '黄帝内经素问遗篇', '编撰人不详  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('454', '452-素问要旨论.txt', '素问要旨论', '刘完素  ', '金  ', '公元1115-1234年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('455', '453-黄帝素问宣明论方.txt', '黄帝素问宣明论方', '刘完素  ', '金  ', '公元1115-1234年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('456', '454-难经集注.txt', '难经集注', '王九思  ', '明  ', '公元1505年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('457', '455-难经古义.txt', '难经古义', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('458', '456-万氏秘传片玉心书.txt', '万氏秘传片玉心书', '李子毅  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('459', '', '伤寒论(伤寒杂病论)', '张仲景  ', '东汉  ', '公元25-220年  ', '公元25-220年  ', 'txt', '4');
INSERT INTO `book` VALUES ('460', '458-伤寒捷诀.txt', '伤寒捷诀', '严则庵纂辑、裘庆元辑  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('461', '459-伤寒总病论.txt', '伤寒总病论', '庞安石  ', '宋  ', '公元1100年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('462', '460-类证活人书.txt', '类证活人书', '朱肱  ', '宋  ', '公元960-1127年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('463', '461-注解伤寒论.txt', '注解伤寒论', '成无己  ', '金  ', '公元1144年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('464', '462-伤寒九十论.txt', '伤寒九十论', '许叔微述  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('465', '463-伤寒百证歌.txt', '伤寒百证歌', '许叔微述  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('466', '464-伤寒发微论.txt', '伤寒发微论', '许叔微述  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('467', '465-伤寒明理论.txt', '伤寒明理论', '成无己  ', '宋  ', '公元1142年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('468', '466-仲景伤寒补亡论.txt', '仲景伤寒补亡论', '郭雍  ', '宋  ', '公元1181年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('469', '467-伤寒寻源.txt', '伤寒寻源', '吕震名  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('470', '468-伤寒直格.txt', '伤寒直格', ' ', '金  ', '公元1127年—1279年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('471', '469-伤寒标本心法类萃.txt', '伤寒标本心法类萃', '刘完素  ', '金  ', '公元1115-1234年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('472', '470-伤寒六书.txt', '伤寒六书', '陶华  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('473', '471-伤寒论条辨.txt', '伤寒论条辨', '方有执  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('474', '472-张卿子伤寒论.txt', '张卿子伤寒论', '张卿子  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('475', '473-伤寒证治准绳.txt', '伤寒证治准绳', '王肯堂  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('476', '474-伤寒论注.txt', '伤寒论注', '柯琴  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('477', '475-重订通俗伤寒论.txt', '重订通俗伤寒论', '俞根撰，近代徐荣斋重订。  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('478', '476-伤寒溯源集.txt', '伤寒溯源集', '钱潢  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('479', '477-伤寒括要.txt', '伤寒括要', '李中梓  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('480', '478-伤寒缵论.txt', '伤寒缵论', '张璐  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('481', '479-伤寒贯珠集.txt', '伤寒贯珠集', '尤怡  ', '清  ', '公元1729年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('482', '480-伤寒法祖.txt', '伤寒法祖', '任越庵  ', '宋  ', '公元960-1279年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('483', '481-伤寒大白.txt', '伤寒大白', '高世栻  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('484', '482-伤寒悬解.txt', '伤寒悬解', '黄元御  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('485', '483-伤寒论类方.txt', '伤寒论类方', '徐灵胎  ', '清  ', '公元1759年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('486', '484-伤寒论辩证广注.txt', '伤寒论辩证广注', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('487', '485-伤寒论辑义.txt', '伤寒论辑义', '日本人、丹波元珍着  ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('488', '486-伤寒医诀串解.txt', '伤寒医诀串解', '陈念祖  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('489', '487-伤寒审证表.txt', '伤寒审证表', ' ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('490', '488-伤寒补例.txt', '伤寒补例', '周学海  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('491', '489-敖氏伤寒金镜录.txt', '敖氏伤寒金镜录', '杜本  ', '元  ', '公元1341年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('492', '490-伤寒舌鉴.txt', '伤寒舌鉴', '张登  ', '清·康熙戊申年  ', '公元1668年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('493', '491-增订叶评伤暑全书.txt', '增订叶评伤暑全书', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('494', '492-伤寒论翼.txt', '伤寒论翼', '柯琴  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('495', '493-伤寒附翼.txt', '伤寒附翼', '柯琴  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('496', '494-伤寒指掌.txt', '伤寒指掌', '吴坤安  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('497', '495-中寒论辩证广注.txt', '中寒论辩证广注', '丹波元胤  ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('498', '496-河间伤寒心要.txt', '河间伤寒心要', '镏洪  ', '金  ', '公元1127年—1279年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('499', '497-刘河间伤寒医鉴.txt', '刘河间伤寒医鉴', '马宗素  ', '元代  ', '公元1271年—1368年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('500', '498-金匮要略浅注.txt', '金匮要略浅注', '陈修园  ', '汉  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('501', '499-金匮要略方论.txt', '金匮要略方论', '张仲景  ', '汉  ', '公元219年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('502', '500-金匮要略心典.txt', '金匮要略心典', '尤怡  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('503', '501-金匮玉函经二注.txt', '金匮玉函经二注', '周扬俊  ', '清  ', '公元1687年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('504', '502-金匮玉函要略述义.txt', '金匮玉函要略述义', ' ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('505', '503-脉诀.txt', '金匮篇', '崔嘉彦', '宋', '公元1189年', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('506', '504-脉经.txt', '脉经', '王叔和  ', '西晋  ', '公元280年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('507', '505-诊家枢要.txt', '诊家枢要', '滑寿  ', '元  ', '公元1359年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('508', '506-濒湖脉学.txt', '濒湖脉学', '李时珍  ', '明·嘉靖四十三年  ', '公元1564年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('509', '507-诊家正眼.txt', '诊家正眼', '李中梓  ', '明  ', '公元1642年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('510', '508-三指禅.txt', '三指禅', '周学霆  ', '清  ', '公元1872年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('511', '509-湿热病篇.txt', '湿热病篇', '薛生白   ', '清  ', '  ', '', 'txt', null);
INSERT INTO `book` VALUES ('512', '510-形色外诊简摩.txt', '形色外诊简摩', '周学海  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('513', '511-金匮玉函要略辑义.txt', '金匮玉函要略辑义', '元简  ', '清  ', '公元1806年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('514', '512-脉理求真.txt', '脉理求真', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('515', '513-脉诀刊误.txt', '脉诀刊误', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('516', '514-脉诀汇辨.txt', '脉诀汇辨', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('517', '515-高注金匮要略.txt', '高注金匮要略', '高学山  ', '清  ', '公元1872年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('518', '516-临症验舌法.txt', '临症验舌法', '杨云峰  ', '清  ', '公元1917年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('519', '517-望诊遵经.txt', '望诊遵经', '汪宏  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('520', '518-诊宗三昧.txt', '诊宗三昧', '张璐  ', '清  ', '公元1689年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('521', '519-医灯续焰.txt', '医灯续焰', '潘楫  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('522', '520-察病指南.txt', '察病指南', '施桂堂  ', '宋  ', '公元960年—1279年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('523', '521-察舌辨症新法.txt', '察舌辨症新法', '刘恒瑞  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('524', '522-温疫论.txt', '温疫论', '吴又可  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('525', '523-千金食治.txt', '千金食治', '孙思邈  ', '唐  ', '公元618年－公元907年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('526', '524-温热暑疫全书.txt', '温热暑疫全书', '周扬俊  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('527', '525-疫疹一得.txt', '疫疹一得', '余霖  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('528', '526-温病条辨.txt', '温病条辨', '吴鞠通  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('529', '527-温热逢源.txt', '温热逢源', '柳宝诒  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('530', '528-时病论.txt', '时病论', '雷丰  ', '清  ', '公元1882年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('531', '529-温病指南.txt', '温病指南', '高秉钧  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('532', '530-女丹合编选注.txt', '女丹合编选注', '贺龙骧  ', '清  ', '公元1644──公元1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('533', '531-运气要诀.txt', '运气要诀', '吴谦  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '9');
INSERT INTO `book` VALUES ('534', '532-备急千金要方.txt', '备急千金要方', '孙思邈  ', '唐·永微三年  ', '公元652年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('535', '533-食疗方.txt', '食疗方', ' ', ' ', ' ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('536', '534-心医集.txt', '心医集', '祝登元  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('537', '535-西池集.txt', '西池集', ' ', ' ', ' ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('538', '536-性命要旨.txt', '性命要旨', '汪东亭  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('539', '537-松峰说疫.txt', '松峰说疫', '刘松峰  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('540', '538-寿世传真.txt', '寿世传真', '徐文弼  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('541', '539-陆地仙经.txt', '陆地仙经', '马齐  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('542', '540-宁坤秘笈.txt', '宁坤秘笈', ' ', ' ', ' ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('543', '541-温病正宗.txt', '温病正宗', '王德宣  ', ' ', ' ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('544', '542-寿世保元.txt', '寿世保元', '龚廷贤  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('545', '543-温热经纬.txt', '温热经纬', '王士雄  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('546', '544-温热论.txt', '温热论', '叶桂  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('547', '545-达摩洗髓易筋经.txt', '达摩洗髓易筋经', '项杨惠吴德华张鉴若曹江  ', ' ', ' ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('548', '546-广瘟疫论.txt', '广瘟疫论', '吴又可  ', '明·崇祯末年  ', '公元1641年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('549', '547-养生秘旨.txt', '养生秘旨', '马齐  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('550', '548-养生导引法.txt', '养生导引法', '胡文焕  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('551', '549-重订广温热论.txt', '重订广温热论', '何廉臣  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('552', '550-养生导引秘籍.txt', '养生导引秘籍', '胡文焕  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('553', '551-随息居重订霍乱论.txt', '随息居重订霍乱论', '王士雄  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('554', '552-修昆仑证验.txt', '修昆仑证验', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('555', '553-寿世青编.txt', '寿世青编', '尤乘  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('556', '554-养生类要.txt', '养生类要', '吴正伦  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', '11');
INSERT INTO `book` VALUES ('557', '555-饮食须知.txt', '饮食须知', '贾铭  ', '元代  ', '公元1271年—1368年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('558', '556-瘴疟指南.txt', '瘴疟指南', '郑全望  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('559', '557-华氏中藏经.txt', '华氏中藏经', '华佗  ', '东汉  ', '公元25—220年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('560', '558-三因极一病证方论.txt', '三因极一病证方论', '陈言  ', '宋  ', '公元1174年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('561', '559-扁鹊心书.txt', '扁鹊心书', '窦材  ', '宋  ', '公元1127年—1279年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('562', '560-玉机微义.txt', '玉机微义', '徐彦纯  ', '元明  ', '公元1271-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('563', '561-明医指掌.txt', '明医指掌', '皇甫中  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('564', '562-明医杂着.txt', '明医杂着', '王纶  ', '明  ', '公元1502年-1549年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('565', '563-此事难知.txt', '此事难知', '王好古  ', '元  ', '公元1279-1368年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('566', '564-金匮钩玄.txt', '金匮钩玄', '朱震亨  ', '元  ', '公元1358年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('567', '565-卫生宝鉴.txt', '卫生宝鉴', '罗天益  ', '元  ', '公元1343年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('568', '566-校注医醇剩义.txt', '校注医醇剩义', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('569', '567-脉因证治.txt', '脉因证治', '朱丹溪  ', '清  ', '公元1279-1368年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('570', '568-杂病治例.txt', '杂病治例', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('571', '569-秘传证治要诀及类方.txt', '秘传证治要诀及类方', '戴思恭  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('572', '570-丹溪心法.txt', '丹溪心法', '朱震亨、戴思恭  ', '元末明初  ', '公元1347年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('573', '571-诸病源候论.txt', '诸病源候论', '巢元方  ', '隋  ', '公元614年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('574', '572-儒门事亲.txt', '儒门事亲', '张从正  ', '金  ', '公元1127年—1279年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('575', '573-古今医鉴.txt', '古今医鉴', '龚信  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('576', '574-医说.txt', '医说', '张杲  ', '南宋  ', '公元1127-1279年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('577', '575-医宗金鉴.txt', '医宗金鉴', '吴谦  ', '清  ', '公元1742年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('578', '576-医经国小.txt', '医经国小', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('579', '577-医学入门.txt', '医学入门', '李橚  ', '明  ', '公元1575年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('580', '578-医学启源.txt', '医学启源', '张元素  ', '金  ', '公元1127-1279年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('581', '579-医学纲目.txt', '医学纲目', '楼英  ', '明  ', '公元1565年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('582', '580-医垒元戎.txt', '医垒元戎', '王好古  ', '元  ', '公元1271-1368年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('583', '581-兰室秘藏.txt', '兰室秘藏', '李东垣  ', '金元间  ', '公元1115-1368年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('584', '582-韩氏医通.txt', '韩氏医通', '韩懋  ', '明  ', '公元1522年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('585', '583-医学正传.txt', '医学正传', '虞传  ', '明  ', '公元1515年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('586', '584-医学衷中参西录.txt', '医学衷中参西录', '张锡纯  ', '清  ', '公元1909年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('587', '585-卫济宝书.txt', '卫济宝书', '东轩居士  ', '宋  ', '公元960年—1279年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('588', '586-三消论.txt', '三消论', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('589', '587-石室秘录.txt', '石室秘录', '陈士铎  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('590', '588-丹溪手镜.txt', '丹溪手镜', '朱丹溪  ', '元  ', '公元１２８１—１３５８年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('591', '589-古今名医汇粹.txt', '古今名医汇粹', '罗美  ', '清  ', '公元1644年－公元1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('592', '590-轩岐救正论.txt', '轩岐救正论', '萧京  ', '明  ', '公元1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('593', '591-痧胀玉衡.txt', '痧胀玉衡', '郭士遂  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('594', '592-医学三字经.txt', '医学三字经', '陈修园  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('595', '593-辨证录.txt', '辨证录', '陈士铎  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('596', '594-医学指归.txt', '医学指归', '赵术堂  ', '清  ', '公元1851年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('597', '595-医学实在易.txt', '医学实在易', '陈修园  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('598', '596-医学摘粹.txt', '医学摘粹', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('599', '597-冯氏锦囊秘录.txt', '冯氏锦囊秘录', '冯楚瞻  ', '清代  ', '公元1644-1911年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('600', '598-简明医彀.txt', '简明医彀', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('601', '599-医述.txt', '医述', '程杏轩  ', '元  ', '公元1314年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('602', '600-辨症玉函.txt', '辨症玉函', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('603', '601-医学心悟.txt', '医学心悟', '程国彭  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('604', '602-类证治裁.txt', '类证治裁', '林佩琴  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('605', '603-医碥.txt', '医碥', '何梦瑶  ', '清  ', '公元1751年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('606', '604-医学真传.txt', '医学真传', '高秉钧  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('607', '605-张氏医通.txt', '张氏医通', '张璐  ', '清·康熙三十四年  ', '公元1695年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('608', '606-中国医籍考.txt', '中国医籍考', '丹波元胤  ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('609', '607-脉象统类.txt', '脉象统类', ' ', ' ', ' ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('610', '608-丹台玉案.txt', '丹台玉案', '孙文胤  ', '明  ', '公元1637  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('611', '609-伤寒论纲目.txt', '伤寒论纲目', '沈金鳌  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('612', '610-幼科释谜.txt', '幼科释谜', '沈金鳌  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('613', '611-妇科玉尺.txt', '妇科玉尺', '沈金鳌  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('614', '612-古今医彻.txt', '古今医彻', '怀远  ', '清  ', '公元1644年－公元1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('615', '613-药症忌宜.txt', '药症忌宜', '陈三山  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('616', '614-脾胃论.txt', '脾胃论', '李东垣  ', '金元  ', '公元1249年[公元年起] 11249  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('617', '615-外经微言.txt', '瑰宝苑 《外经微言》', '陈士铎  ', '  ', ' ', '', 'txt', '4');
INSERT INTO `book` VALUES ('618', '616-洗冤集录.txt', '洗冤集录', '宋慈  ', '宋  ', '公元1247-1249年  ', ' ', 'txt', '3');
INSERT INTO `book` VALUES ('619', '617-古今医统大全.txt', '古今医统大全', '徐春甫  ', '明  ', '公元1556年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('620', '618-格致余论.txt', '格致余论', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('621', '619-验方家秘.txt', '验方家秘', '山野居士  ', '  ', '', '', 'txt', null);
INSERT INTO `book` VALUES ('622', '620-推求师意.txt', '推求师意', '戴思恭  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('623', '621-褚氏遗书.txt', '褚氏遗书', '褚澄  ', '南齐  ', '公元420年—589年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('624', '622-诸脉主病诗.txt', '诸病主病诗', '东轩居士  ', '宋  ', '公元960年—1279年  ', ' ', 'txt', '10');
INSERT INTO `book` VALUES ('625', '623-医旨绪余.txt', '医旨绪余', '孙一奎  ', '明  ', '公元1368-1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('626', '624-医宗己任编.txt', '医宗己任编', '高鼓峰  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('627', '625-医学妙谛.txt', '医学妙谛', '何其伟  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('628', '626-医学见能.txt', '医学见能', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('629', '627-顾松园医镜.txt', '顾松园医镜', '顾靖远  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('630', '628-医医小草.txt', '医医小草', '宝辉  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('631', '629-眼科奇书.txt', '眼科奇书', '不详 ,系清代渝州(今重庆市)李氏家藏秘本', '未知  ', '未知 ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('632', '630-医学传灯.txt', '医学传灯', '陈歧  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('633', '631-医法圆通.txt', '医法圆通', '郑寿全著', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('634', '632-证治准绳·类方.txt', '证治准绳·类方', '王肯堂  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '2');
INSERT INTO `book` VALUES ('635', '633-证治准绳·伤寒.txt', '证治准绳·伤寒', '王肯堂  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('636', '634-幼科种痘心法要旨.txt', '幼科种痘心法要旨', '吴谦  ', '清  ', '公元1644-1911年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('637', '635-证治准绳·幼科.txt', '证治准绳·幼科', '王肯堂  ', '明  ', '公元1368年—1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('638', '636-证治准绳·女科.txt', '证治准绳·女科', '王肯堂  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('639', '637-景岳全书.txt', '景岳全书', '张介宾  ', '明  ', '公元1640年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('640', '638-订正仲景全书伤寒论注.txt', '订正仲景全书伤寒论注', '吴谦  ', '清  ', '公元1742年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('641', '639-删补名医方论.txt', '删补名医方论', '吴谦  ', '清  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('642', '640-宜麟策.txt', '宜麟策', '佚 名  ', '清  ', '公元1644年—1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('643', '641-医理真传.txt', '医理真传', '郑钦安  ', '清  ', ' ', '', 'txt', '4');
INSERT INTO `book` VALUES ('644', '642-订正仲景全书金匮要略注.txt', '订正仲景全书金匮要略注', ' ', ' ', ' ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('645', '643-证治准绳·疡医.txt', '证治准绳·疡医', '王肯堂  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('646', '644-证治准绳·杂病.txt', '证治准绳·杂病', '王肯堂  ', '明  ', '公元1368-1644年  ', ' ', 'txt', '5');
INSERT INTO `book` VALUES ('647', '645-证类本草.txt', '证类本草', '唐慎微  ', '宋  ', '公元960-1279年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('648', '646-伤寒心法要诀.txt', '伤寒心法要诀', '吴谦  ', '清朝  ', '公元1644-1911年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('649', '647-万病回春.txt', '万病回春', '龚廷贤  ', '明  ', '公元1615年  ', ' ', 'txt', null);
INSERT INTO `book` VALUES ('650', '648-医津一筏.txt', '医津一筏（一名《内经释要》）', '歙县  江之兰  含征  著 ', '  ', '', '', 'txt', null);
INSERT INTO `book` VALUES ('651', '649-续医说.txt', '续医说', '俞弁  ', '明  ', '公元1545年  ', ' ', 'txt', '4');
INSERT INTO `book` VALUES ('652', '650-医脉摘要.txt', '瑰宝苑 医脉摘要', '萧廉泉  ', '  ', '  ', '', 'txt', '4');
INSERT INTO `book` VALUES ('653', '651-十二經補瀉溫涼引經藥歌.txt', '十二經補瀉溫涼引經藥歌', '', '', '', '', 'txt', '1');
INSERT INTO `book` VALUES ('654', '652-三时伏气外感篇.txt', '三时伏气外感篇', '', '  ', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('655', '653-辅行诀脏腑用药法要.txt', '辅行诀脏腑用药法要', '华阳隐居 陶弘景', '梁  ', '', '', 'txt', '1');
INSERT INTO `book` VALUES ('656', '654-伤寒辨要笺记.txt', '伤寒辨要笺记', '日·浅田惟常', '现代  ', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('657', '655-评琴书屋医略.txt', '评琴书屋医略', '', '  ', '', '', 'txt', '5');
INSERT INTO `book` VALUES ('658', '656-类证普济本事方续集.txt', '类证普济本事方续集', '', '  ', '', '', 'txt', '5');
INSERT INTO `book` VALUES ('659', '657-澄空民间中医学精髓论.txt', '澄空民间中医学精髓论', '刘文澄', '  ', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('660', '658-医学传心录.txt', '医学传心录', '钱乐天 郭中元 孙桐轩', '  清', '道光年间', '', 'txt', '4');
INSERT INTO `book` VALUES ('661', '659-民间草药药性赋.txt', '民间药性赋', '山野居士 ', '  ', '', '', 'txt', '1');
INSERT INTO `book` VALUES ('662', '660-程门雪遗稿.txt', '程门雪遗稿', '程门雪 ', '  ', '1902-1972', '', 'txt', '3');
INSERT INTO `book` VALUES ('663', '661-七十二症辨治方法.txt', '未知', '未知', '未知', '未知', '', 'txt', null);
INSERT INTO `book` VALUES ('664', '662-仿寓意草.txt', '仿寓意草', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('665', '', '洄溪医案', '徐灵胎', '清', '未知', '未知', 'txt', '3');
INSERT INTO `book` VALUES ('666', '664-许氏医案.txt', '许氏医案', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('667', '', '医病简要', '未知', '未知', '未知', '未知', 'txt', '3');
INSERT INTO `book` VALUES ('668', '666-一瓢医案.txt', ' 一瓢医案', '薛雪生白著,吴金寿子音篡', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('669', '667-医验随笔.txt', ' 医验随笔', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('670', '668-玉台新案.txt', '玉台新案', '徐镛', '清  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('671', '669-名师垂教.txt', '名师垂教-医案', '肖永林', '现代  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('672', '670-陈友芝医案.txt', '陈友芝医案', '陈友芝', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('673', '671-范中林六经辨证医案.txt', '范中林六经辨证医案', '范中林', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('674', '672-经方实验录.txt', '经方实验录', '曹颖甫', '民国', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('675', '673-旧德堂医案.txt', '旧德堂医案', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('676', '674-吴佩衡医案.txt', '吴佩衡医案', '吴佩衡', '  现代', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('677', '675-姚贞白医案.txt', '', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('678', '676-医学经验录·医案.txt', '医学经验录·医案', '熊惠生', ' 现代', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('679', '677-诊余举隅录.txt', '诊余举隅录', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('680', '678-醉花窗医案.txt', '醉花窗医案', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('681', '679-章次公医案.txt', '章次公医案', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('682', '680-增补评注柳选医案.txt', '增补评注柳选医案', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('683', '681-赵绍琴临证验案精选上.txt', '赵绍琴临证验案精选上', '赵绍琴', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('684', '682-戴丽三医疗经验选.txt', '戴丽三医疗经验选', '戴丽三', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('685', '683-近现代名医验案类编.txt', '近现代名医验案类编', '', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('686', '684-三十年临证经验集.txt', '三十年临证经验集', '邹孟城', '当代  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('687', '685-复泰草堂医论选.txt', '复泰草堂医论选', '三七生', '  ', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('688', '686-中医临证经验与方法.txt', '中医临证经验与方法', '朱进忠', ' 现代', '2002年4月  ', '', 'txt', '5');
INSERT INTO `book` VALUES ('689', '687-经穴秘密.txt', '经穴秘密', '', '  ', '', '', 'txt', '8');
INSERT INTO `book` VALUES ('690', '688-十四经发挥.txt', '十四经发挥', '滑寿撰', ' 元 ', '', '', 'txt', '8');
INSERT INTO `book` VALUES ('691', '689-百家针灸歌赋.txt', ' 百家针灸歌赋', '', '  ', '', '', 'txt', '8');
INSERT INTO `book` VALUES ('692', '690-黄帝内经十二经脉秘与应用.txt', '黄帝内经十二经脉秘与应用', '祝华英', '  ', '', '', 'txt', '8');
INSERT INTO `book` VALUES ('693', '691-中国民间刺血术（节选）.txt', '中国民间刺血术（节选）', '刘少林刘光瑞', ' 现代', '', '', 'txt', '8');
INSERT INTO `book` VALUES ('694', '692-鲙残篇.txt', '景景医话', '', '  ', '', '', 'txt', '5');
INSERT INTO `book` VALUES ('696', '694-推逢寤语 医林琐语.txt', '推篷寤语', '李豫亨元荐', '  ', '', '', 'txt', '11');
INSERT INTO `book` VALUES ('697', '695-医中一得 医医十病.txt', '医中一得', '梁溪, 顾尔元', '清  ', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('698', '', '士谔医话', '陆士谔', '  ', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('699', '697-止园医话.txt', '', '未知', '未知', '未知', ' ', 'txt', null);
INSERT INTO `book` VALUES ('700', '698-脉诀阐微 脉学阐微.txt', '脉诀阐微（修订版）', '陈士铎', '  清', '', '', 'txt', '10');
INSERT INTO `book` VALUES ('701', '699-名老中医之路.txt', ' 名老中医之路', '汪逢春', '  ', '一八八四年五月二十九', '', 'txt', '4');
INSERT INTO `book` VALUES ('712', '', '易经说卦传', '未知', '先秦', '未知', '未知', 'txt', '12');
INSERT INTO `book` VALUES ('713', '', '周易', '周文王', '周朝', '周朝', '周朝', 'txt', '12');
INSERT INTO `book` VALUES ('714', '', '龙图说医', '龙图', '当代', '当代', '易医', 'txt', '4');
INSERT INTO `book` VALUES ('715', '', '圆运动的古中医学', '彭子益', '当代', '1949', '', 'txt', '4');
INSERT INTO `book` VALUES ('716', '', '老子', '李耳', '春秋', '春秋', '又称《道德经》，道家经典，其中大道存。\r\n', 'txt', '16');
INSERT INTO `book` VALUES ('717', '', '孙子兵法', '孙武', '春秋战国', '', '兵家之经。', 'txt', '16');
INSERT INTO `book` VALUES ('718', '', '专病专制-网上收集', '网友', '当代', '2008', '专病专治方面网上的资料', 'txt', '5');
INSERT INTO `book` VALUES ('719', '', '中医散文-网上收集', '网友', '当代', '2008', '', 'txt', null);
INSERT INTO `book` VALUES ('720', '', '中医与武术', '站长收集', '当代', '2008', '武术与医理密不可分， 古代技击大家往往也是明中医。 \r\n', 'txt', null);
INSERT INTO `book` VALUES ('721', '', '峨嵋拳谱', '未知', '未知', '未知', '未知', 'txt', '11');
INSERT INTO `book` VALUES ('722', '', '马王堆简帛', '未知', '未知', '未知', '', 'txt', '15');
INSERT INTO `book` VALUES ('723', '', '素女经', '黄帝', '上古', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('724', '', '洞玄子', '洞玄子', '当代', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('725', '', '养性延命录', '陶弘景', '南朝', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('726', '', '素女妙论', '素女', '未知', '未知', '', 'txt', '15');
INSERT INTO `book` VALUES ('727', '', '房内记', '', '古代', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('728', '', '古今图书集成医部全录-黄帝内经', '陈梦雷等编', '清', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('729', '', '褚氏遗书', '褚澄', '南齐', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('730', '', '房中补益', '孙思邈', '唐', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('731', '', '既济真经', '未知', '未知', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('732', '', '紫金光耀大仙修真演义', '邓希贤', '汉', '汉元丰三年', '', 'txt', '15');
INSERT INTO `book` VALUES ('733', '', '三元参赞延寿书', '李鹏飞', '元', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('734', '', '摄生总要', '洪基', '明', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('735', '', '金刚经(金刚般若波罗蜜经)', '佛', '古代', '', '', 'txt', '16');
INSERT INTO `book` VALUES ('736', null, '许氏医案', '许恩普', '清末', '', '', 'txt', '3');
INSERT INTO `book` VALUES ('737', null, '秘本种子金丹', '叶天士', '清', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('738', null, '妙一斋医学正印种子编', '岳甫嘉', '明', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('739', null, '广嗣纪要', '万全', '明', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('740', null, '广嗣要语', '俞桥', '明', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('741', null, '广嗣五种备要-种子心法', '王实颖', '清', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('742', null, '宜麟策', '', '明', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('743', null, '花柳指迷', '林东湘', '清', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('744', null, '男女房中秘密医术', '怡养老人', '民国', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('745', null, '螽斯秘诀', '', '未知', '', '', 'txt', '15');
INSERT INTO `book` VALUES ('746', null, '梅花易数', '邵康节', '宋', '', '', 'txt', '12');
INSERT INTO `book` VALUES ('747', null, '达摩易筋经(版本二)', '达摩祖师', '当代', '', '', 'txt', '11');
INSERT INTO `book` VALUES ('750', null, '易经杂说', '南怀瑾', '当代  ', ' ', '', 'txt', '12');
INSERT INTO `book` VALUES ('751', null, '催官篇', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('752', null, '发微论', ' 蔡牧堂', '未知  ', '《》', '', 'txt', '14');
INSERT INTO `book` VALUES ('753', null, '天元歌', ' 蒋大鸿', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('754', null, '天玉经', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('755', null, '廖禹十六葬法', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('756', null, '撼龙经', ' 杨筠松', '唐', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('757', null, '灵城精义', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('758', null, '玄机赋', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('759', null, '玄空秘旨 ', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('760', null, ' 逐吉赋 ，又名玉尺经', '杨筠松', '唐  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('761', null, '玉尺经·逐吉赋', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('762', null, '疑龙经', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('763', null, '管氏地理指蒙', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('764', null, '紫白赋', ' 未知', '未知  ', ' ', '', 'txt', '14');
INSERT INTO `book` VALUES ('765', null, '罗经透解', ' 王道亨', '未知  ', '清代', '', 'txt', '14');
INSERT INTO `book` VALUES ('766', null, '葬书', ' 未知', '未知  ', ' ', '', 'txt', '14');
INSERT INTO `book` VALUES ('767', null, '葬法倒杖', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('768', null, '都天宝照经', ' 蒋大鸿', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('769', null, '金关玉锁诀', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('770', null, '金锁玉关（过路阴阳）实例大全', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('771', null, '金锁玉关 经文 ', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('772', null, '阳宅指南', ' 蒋大鸿', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('773', null, '青乌先生葬经', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('774', null, '青囊奥语', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('775', null, '青囊序', ' 曾文迪', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('776', null, '风水理论简析', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('777', null, '飞星赋', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('778', null, '黄帝宅经', ' 未知', '未知  ', '', '', 'txt', '14');
INSERT INTO `book` VALUES ('779', null, '医医十病', '吴楚天士', '清', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('780', null, '医林琐语', '元和 陆懋修九芝', '  清', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('781', null, '脉学阐微', '邢锡波', '  ', '', '', 'txt', '10');
INSERT INTO `book` VALUES ('782', null, '《六爻新大陆》高级班讲义', ' 未知', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('783', null, '六爻三大技法', '黎光', '未知  ', '2003-5-1', '', 'txt', '13');
INSERT INTO `book` VALUES ('784', null, '六爻入门', '未知', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('785', null, '六爻婚姻卦理', '小杨整理', '当代 ', '2008', '', 'txt', '13');
INSERT INTO `book` VALUES ('787', null, '六爻精义', ' 未知', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('788', null, '六爻精华荟萃', '未知', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('789', null, '六爻阴阳经', ' 未知', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('790', null, '卜筮正宗', ' 未知', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('791', null, '易冒', '程良玉,旅堂胡', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('792', null, '火珠林', '麻衣道者', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('793', null, '续六爻新大陆', ' 未知', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('794', null, '增删卜易', '野鹤老人,李我平,李文辉', '未知  ', '', '', 'txt', '13');
INSERT INTO `book` VALUES ('795', null, '鬼谷子神相全编', '麻衣道者', '未知  ', '', '', 'txt', '17');
INSERT INTO `book` VALUES ('796', null, '绘图神相铁关刀', '未知', '未知  ', '未知', '', 'txt', '17');
INSERT INTO `book` VALUES ('797', null, '公笃相法', '   陈公笃', '未知', '未知', '', 'txt', '17');
INSERT INTO `book` VALUES ('798', null, '冰鉴', '曾国藩', '清', '　', '', 'txt', '17');
INSERT INTO `book` VALUES ('799', null, '相术-骨骼篇', '未知', '未知', '未知', '', 'txt', '17');
INSERT INTO `book` VALUES ('800', '', '六十五经典相术歌诀汇编', '杨同峰编攥', '未知', '未知', '未知', 'txt', '17');
INSERT INTO `book` VALUES ('801', null, '达摩祖师相诀秘传', '达摩祖师', '', '', '', 'txt', '17');
INSERT INTO `book` VALUES ('802', null, '铁关刀', '未知', '未知', '未知　', '', 'txt', '17');
INSERT INTO `book` VALUES ('803', null, '许负相法十六篇', '未知', '未知', '未知　', '', 'txt', '17');
INSERT INTO `book` VALUES ('804', null, '神相全编', '', '', '　', '', 'txt', '17');
INSERT INTO `book` VALUES ('805', null, '知命识相五十年', '韦千里', '近代', '未知　', '', 'txt', '17');
INSERT INTO `book` VALUES ('806', null, '相法节录', '未知', '未知', '未知　', '', 'txt', '17');
INSERT INTO `book` VALUES ('807', null, '月波洞中记', '未知', '未知', '未知　', '', 'txt', '17');
INSERT INTO `book` VALUES ('808', null, '麻衣相法通俗读本', '麻衣道人', '', '　', '', 'txt', '17');
INSERT INTO `book` VALUES ('809', '', '黄勇智八字命理学', '黄勇智', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('810', null, '2004涵辰命理高级面授教材合订本', '李涵辰', '当代', '2004年8月', '', 'txt', '18');
INSERT INTO `book` VALUES ('811', null, '中国新派八字绝学 ', '李涵辰', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('812', null, '人鉴--命理存验67例', '林庚白', '民国', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('813', null, '人鉴命理存验50例', '', '', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('814', null, '八字六亲秘诀录', '陈力平', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('815', '', '八字实战讲义', '赵知易，孙海义', '', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('816', null, '八字真踪', '李涵辰', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('817', null, '八字破六亲研究', '易隐燕 ', '', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('818', null, '八字绝学讲义', '', '', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('819', null, '八字高级讲师班教材', '李顺祥', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('820', null, '涵辰命学(涵辰命理)', '李涵辰', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('821', null, '卜文命学新集', '卜文', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('822', null, '四柱阴阳经', '', '', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('823', null, '实践应验断语八百条', '', '', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('824', null, '新派八字经验集', '李涵辰', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('825', null, '李涵辰命理中级面授班课堂实录', '李涵辰', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('826', null, '涵辰预测连载 ', '李涵辰', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('827', '', '滴天命理新论', '张绍金', '当代', '', '', 'txt', null);
INSERT INTO `book` VALUES ('828', null, '漫谈命理学 ', '李顺祥', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('829', null, '略谈解灾', '李顺祥', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('830', null, '祥泰拾珠－各家命理荟萃', '各门各派', '', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('831', null, '窥破玄机', '李顺祥', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('832', '', '四柱八字论坛实践', '网友', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('833', null, '八字入门(八字轻松入门)', '未知', '未知  ', '', '', 'txt', null);
INSERT INTO `book` VALUES ('834', null, '中医之钥(医钥)', '彭奕竣', '近现代', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('835', null, '伤寒杂病论义疏', '刘瑞瀜', '未知  ', '', '', 'txt', '2');
INSERT INTO `book` VALUES ('836', null, '倪海厦文集', '倪海厦', '当代', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('837', '', '洞垣秘笈之洞天奥旨', '陈士铎', '清', '', '', 'txt', '4');
INSERT INTO `book` VALUES ('838', null, ' 腦中風放血救命', '彭奕竣', '近现代', '', '', 'txt', null);
INSERT INTO `book` VALUES ('839', null, '辨证录', '陈士铎', '清', '', '', 'txt', '5');
INSERT INTO `book` VALUES ('841', null, '金匮要略浅言', '未知', '未知  ', '', '', 'txt', '5');
INSERT INTO `book` VALUES ('842', null, '学习奇门-奇门遁甲心盘秘诀', '网友', '当代', '', '', 'txt', null);
INSERT INTO `book` VALUES ('843', null, '奇门演卦', '', '', '', '', 'txt', null);
INSERT INTO `book` VALUES ('844', null, '静坐修道与长生不老', '南怀瑾', '当代 ', '', '', 'txt', null);
INSERT INTO `book` VALUES ('845', null, '求医不如求己', '中里巴人', '当代  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('846', null, '人体使用手册', '吴清忠', '当代  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('847', null, '将中医进行到底-朱德谈养生', '朱德谈', '当代  ', ' ', '', 'txt', null);
INSERT INTO `book` VALUES ('848', null, '对话中医妇科名家柴嵩岩：现在女人那些事儿', '田原', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('849', null, '对话中医妇科名家柴嵩岩：现在女人那些事儿', '田原', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('850', null, '百家讲坛：千古中医故事(选载)', '孙立群、王立群、纪连海等', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('851', null, '恢复中医本来面目：字里藏医', '徐文兵', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('852', null, '曲黎敏中医养生完全手册：从头到脚说健康(选载)', '曲黎敏', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('853', null, '美食美客', '《美食美客》栏目组', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('856', null, '金宏柱教授讲述海外行医故事：中医走天下(节选)', '金宏柱', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('860', null, '中医诊断学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('862', null, '中医儿科学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('863', null, '中医养生学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('864', null, '中医内科学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('865', null, '中医基础理论', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('866', null, '中医外科学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('867', null, '中医妇科学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('868', null, '中医眼科学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('869', null, '中医诊断学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('870', null, '中药基本理论知识', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('871', null, '中西医结合耳鼻喉科', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('872', null, '中药学', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('873', null, '中医刺灸', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('874', null, '中医疾病预测', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('875', null, '中药法规', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('876', null, '中药炮制', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('877', null, '保健药膳', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('878', null, '减肥新法与技巧', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('879', null, '地震灾后常见病多发病中医药治疗手册', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('880', null, '小儿常见病单验方', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('881', null, '常用化验值及意义', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('882', null, '常见病自测', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('883', null, '手穴手纹诊治', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('884', null, '百病自测', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('885', null, '老年食养食疗', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('886', null, '自我调养巧治病', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('887', null, '茶饮保健', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('888', null, '趣味中医', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('889', null, '食物疗法', '', '当代', '', '', 'html', null);
INSERT INTO `book` VALUES ('890', null, '五运六气入门－运气学入门', null, '当代', '2008', '', 'txt', '9');
INSERT INTO `book` VALUES ('892', null, '李洪成六爻答疑500问', '李洪成', '当代', '', '', 'txt', null);
INSERT INTO `book` VALUES ('893', '女人相研究.swf', '女人相研究 ', '易天生', '现代', '', '1   女人相研究\r\n由于比较长，我有空就给大家更新～～～～\r\n作者： 易天生\r\n\r\n第一章 淫蕩相 \r\n\r\n第二章 刑克相 \r\n\r\n第三章 感情婚姻 \r\n\r\n第四章 性格篇 \r\n\r\n第五章 谈命运 \r\n\r\n第六章 际遇篇 \r\n\r\n第七章 财运篇 \r\n\r\n第八章 身心健康 \r\n\r\n第九章 五行篇 \r\n\r\n第十章 杂论  \r\n\r\n第十一章 附：破金锁\r\n\r\n第一章　　淫蕩相 \r\n\r\n1.1 桃花运種種\r\n「桃花运」，听到这名词，大家都不会陌生的。一到新年，大家不是都买一棵桃花回家吗？目的只是想自己行行桃花运，其实桃花运有很多种，常见的有正桃花、偏桃花、桃花面和桃花眼等，更有些是桃花劫和桃花杀，这两样东西保证没有任何人喜欢的。\r\n有些人特别有迷人的魅力，我们可以看看他的双眼，注意是否有「眼带桃花」的现象，这种相的双眼似笑非笑，下眼睑向上弯、田宅宫凹陷，且长期像有泪光浮现，从某些影星艺人双眼常常可看到，这种桃花眼的人最适合做艺人。\r\n如普通女性有桃花眼的话，会麻烦多多，因为这类女性有以下的性格：一、多愁善感；二、心灵极空虚；三、命运起跌很大，喜乐时常互相交替中；四、善变、任性和感受性太强；五、有一种令异性一见倾心的吸引力。因此有着上面性格的人，很容易缠绕在多角恋爱中。离离合合，且以痛苦收场者居多。我建议最好能找一份有关艺术的工作，把全副精神贯注下去，必定有骄人的成就，否则其感情太过泛滥之下，很容易做成不可预期的不幸。就算是多麽有吸引力，令异性神魂颠倒也没用了。\r\n', 'flash', '17');
INSERT INTO `book` VALUES ('894', '', '滴天髓(董序)', '董小明', '当代', '', '', 'undefined', '18');
INSERT INTO `book` VALUES ('895', '', '吕文艺八字', '吕文艺', '现代', '', '吕  氏  八  字  教  材\r\n第一章       总       论\r\n八字命理学理论包括：一、动静；二、进退气；三、命运岁三者的作用程序；四、十神作用方式的吉凶意义；五、流通等五\r\n个系统。\r\n在命运预测实践中，有“四个提倡”：一、提倡只测求测者本人之人事，不测其六亲之人事，要测六亲之人事，拿六亲的八字\r\n来。因为本人之人事是第一信息，六亲之人事是第二信息，第一信息明显准确，第二信息模糊不准确。二、提倡只测求测者\r\n所求测之人事，不测求测者未问之人事。因为八字相同的人，有个命运能量的发挥方向问题，只有按照求测者的命运能量的\r\n发挥方向进行预测，才能做到       。所谓命运能量的发挥方向就是指：相同八字之人，虽然其命运类型相同，但命运能量的\r\n大小程度却各不相同，就是命运能量大小相同的同八字之人，也常常因为其命运能量向财、官、婚姻、健康、寿命、子女等\r\n方向所发挥的能量大小各不相同而使得相同八字之人也有很大的命运差异，因为每一个人的命运能量是一定量的，不是无限\r\n的，这个一定量的命运能量如果发挥在子女、健康、婚姻上的命运能量很多的话，那么能够发挥在财、官上的能量就很少\r\n了，因此说，命运能量的发挥方向是产生相同八字之人命运各不相同的原因之一。三、提倡只测求测者所求测人事之吉凶定\r\n性，不测其人事之吉凶定量。因为即使是相同八字之人，也因为其命运能量的大小程度不同，而其命运差距很大（医院里同\r\n时辰出生的同性别婴儿，有的存活下来长大成人，有的一出生就死亡或是残疾就是证明）因为其命运差距很大，所以要想从\r\n一个时间性的八字中预测出人事的吉凶定量纯属是梦想，通过八字预测人事吉凶定量不但在理论上是不成立的，就是在实践\r\n中也是经不住检验的，虽然从古到今有不少学者苦心研究实践，但总归是毫无进展，即便偶而有一两个狂妄之人喧哮几下，\r\n也是狂犬吠日，枉自耗神，因为客观存在的真理（时间的局限性）是不以人的主观意志为转移的。而通过八字预测人事的吉\r\n凶定性却是既符合客观存在的真理（八字时间决定人的命运类型），又能经得住实践的检验。四、提倡全方位全面预测时\r\n（即财、官、伤病、婚姻、官司、牢狱等全部进行预测），分事项独立进行预测（即先将几年或一生财运测完后，再测官\r\n运，再测伤病，婚姻等等），因为在预测中，同样是枭印合财的十神作用方式，但在不同的命运求测方向上，其吉凶意义差\r\n距很大，如在测财运时，是投资；测官运时，是破耗财求发展；测官司为是非等等，在不同的命运预测方向中，其吉凶意义\r\n各不相同，只有分事项独立进行预测，才能做到铁口直断。\r\n第二章   动   静\r\n动静是决定命局各干支和大运干支有没有生克权的最本质因素。动则有生克权，为有用；静则无生克权，虽有如无，视为无\r\n用。\r\n所谓动，就是指命局干支受到大运干支或流年（流月）干支的刑冲合害；就是指大运干支受到流年（流月）干支的刑冲合\r\n害；所谓静，就是命局干支没有受到大运干支或流年（流月）干支的刑冲合害；就是指大运干支没有受到流年（流月）干支\r\n的刑冲合害。命局干支在没有受到大运干支或流年（流月）干支的作用时，不论动静，为什么原命局不论动静呢？因为只要\r\n该八字之人还活着，那么其原命局干支不论是刑冲合害的多么严重，都说明这种严重的刑冲合害是平衡的，是一个稳定的系\r\n统，只有在岁运干支的参与作用下，这种严重的刑冲合害的动态平衡稳定系统才会被打破，才会出现动与静的分别，这就好\r\n像是一辆十分破旧的汽车，只要其能正常行驶，就说明这辆汽车的各个系统虽然都有毛病，却是一个平衡的稳定的系统，无\r\n所谓具体的哪一个系统有毛病，只有在某一系统突然受到外力作用（如同岁运干支）时，才能改变这个系统的平衡性和稳定\r\n性，也才能进而影响整个车辆的平衡性和稳定性，比如轮胎突然被钉子扎破爆炸了，车辆突然因轮胎爆炸而倾斜，由倾斜产\r\n生的重心偏移，又使得车轴折断，由车轴折断而又引起闸箱中齿轮的损坏等等。命局亦同此理，在原命局中干支是不论动静\r\n的，只有在岁运干支的作用下，原命局中的干支才有动静的分别。\r\n注意：  、大运干或支与命局中干或支相同时，为到位，到位即为发动，到位之干或支有生克权。\r\n、日主发动时，力量大，受生受克强烈；日主不发动为静，力量小，受生受克力度小。\r\n、日主不论动还是静，都受生  克  ，但不能去生  克  其它干支。即日主不论动还是静，都有受生  克  权，但无生  克  它\r\n权。\r\n、生克权就是受生  克  ，生  克  它权利，有生克权就是指有受生  克  的权利，有生  克  它权利；无生克权就是既不能受它\r\n干支生  克  ，也不能去生  克  它干支。无生克权也就是虽有如无，不起任何作用。\r\n、流年干支如果与大运干支没有刑冲合害之关系，那么大运干支就不参与到命局中去生克，大运干支即为静，为无生克\r\n权。\r\n、吉凶皆由动而产生，不动则无生克权，逢流年引发不了命局和大运各干支发动时，该流年为平淡无奇之常年，逢流月引\r\n发干支发动时，有小事发生。\r\n、只有当大运干支与命局各干支有刑冲合害、到位之关系时，命局干支才论动静；只有当流年干支与大运干支和命局各干\r\n支有刑冲合害、到位五种关系时，命局干支和大运干支才论动静。只有动才有生克权，日主不论动还是静，都有受生受克\r\n权，没有生它或克它权。', 'flash', '18');
INSERT INTO `book` VALUES ('896', '周易六十四卦通解.swf', '周易六十四卦通解', '未知', '现代', '', '', 'flash', '12');
INSERT INTO `book` VALUES ('897', '子平真诠评注.swf', '子平真诠评注', '徐乐吾', '民国', '', '', 'flash', '18');
INSERT INTO `book` VALUES ('898', '滴天髓-任注.swf', '滴天髓阐微', '刘伯温 任铁礁', '', '', '', 'flash', '18');
INSERT INTO `book` VALUES ('899', '王梦英医话.swf', '王梦英医话', '王梦英', '', '', '', 'flash', '3');
INSERT INTO `book` VALUES ('900', '纳甲筮法.swf', '纳甲筮法', '刘大钧', '', '', '', 'flash', '12');
INSERT INTO `book` VALUES ('901', null, '千里命稿', '韦千里', '当代', '', '', 'txt', '18');
INSERT INTO `book` VALUES ('902', '玄通功.swf', '玄通功', '', '当代', '', '', 'flash', null);
INSERT INTO `book` VALUES ('903', null, '王凤麟奇门遁甲课堂实录', '王凤麟', '当代', '', '', null, null);
INSERT INTO `book` VALUES ('904', null, '中医实践医话录', '魏长春', '当代', '', '', null, '4');
INSERT INTO `book` VALUES ('905', null, '性命双修万神圭旨', '元集', '当代', '', '', null, null);
INSERT INTO `book` VALUES ('906', null, '半隐居士慈悲开示录', '半隐居士', '未知', '', '', null, null);
INSERT INTO `book` VALUES ('907', null, '神奇的八卦象数疗法', '', '当代', '', '', null, null);
INSERT INTO `book` VALUES ('908', null, '皇极经世', '邵雍（邵康节）', '明', '', '　　《皇极经世》共十二卷六十四篇。首六卷《元会运世》凡三十四篇，次四卷《声音律品》凡十六篇，次《观物内篇》凡十二篇，末《观物外篇》凡二篇。前六十二篇是邵氏自著，末二篇是门人弟子记述。\r\n\r\n　　《皇极经世》是一部运用易理和易数推究宇宙起源、自然演化和社会历史变迁的著作，以河洛、象数之学显于世。其中《观物篇》实乃邵雍之哲学、易理、历史学的理论大纲。\r\n\r\n　　《皇极经世》堪称中国思想史上的奇书，玄思异想，古所罕见。仁者见仁，智者见智。抑之者贬为“空中楼阁”，尊之者谓其“学达性天”。儒道兼综的“经世”宏论，发前人之未发。邵雍其人，“安乐窝”中隐居三十年，洛阳城里，“行窝”十二家；达官显贵邀为座上嘉宾，里巷姑嫂，亲切呼之“家先生”；政治上超脱，思想上开拓，生活上洒脱。书名“经世”而不赖以用世，诗标“击壤”乃自别于大雅。怀奇才，写奇书，诚然北宋一怪杰。 ', null, null);
INSERT INTO `book` VALUES ('909', 'null', 'ss', 'null', 'null', 'null', 'null', 'null', '1');
INSERT INTO `book` VALUES ('910', 'null', 'ss', 'null', 'null', 'null', 'null', 'null', '1');
INSERT INTO `book` VALUES ('911', 'null', 'ss', 'null', 'null', 'null', 'null', 'null', '1');
INSERT INTO `book` VALUES ('912', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('913', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('914', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('915', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('916', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('917', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('918', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('919', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('920', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('921', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('922', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('923', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('924', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('925', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('926', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('927', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('928', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('929', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('930', null, 'ss', null, null, null, null, null, '1');
INSERT INTO `book` VALUES ('931', null, 'ss', null, null, null, null, null, '1');

-- ----------------------------
-- Table structure for catalog
-- ----------------------------
DROP TABLE IF EXISTS `catalog`;
CREATE TABLE `catalog` (
  `name` varchar(50) default NULL,
  `id` int(11) NOT NULL auto_increment,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of catalog
-- ----------------------------
INSERT INTO `catalog` VALUES ('本草', '1');
INSERT INTO `catalog` VALUES ('方剂', '2');
INSERT INTO `catalog` VALUES ('医案', '3');
INSERT INTO `catalog` VALUES ('经论', '4');
INSERT INTO `catalog` VALUES ('专科', '5');
INSERT INTO `catalog` VALUES ('炮制', '7');
INSERT INTO `catalog` VALUES ('针灸', '8');
INSERT INTO `catalog` VALUES ('五运六气', '9');
INSERT INTO `catalog` VALUES ('诊断', '10');
INSERT INTO `catalog` VALUES ('养生', '11');
INSERT INTO `catalog` VALUES ('周易', '12');
INSERT INTO `catalog` VALUES ('六爻', '13');
INSERT INTO `catalog` VALUES ('风水', '14');
INSERT INTO `catalog` VALUES ('房事', '15');
INSERT INTO `catalog` VALUES ('佛道', '16');
INSERT INTO `catalog` VALUES ('相术', '17');
INSERT INTO `catalog` VALUES ('八字', '18');
